### ISSUE TITLE
Implement caching of gh requests

### ISSUE THREAD

**Issue by joelmccracken** [thinkthroughmath/dev_wizard#11]
Requests from the Github gateway should be cached. Currently, we can do about 20 PR TODO web requests per hour before we hit the limit on GH. This won't scale.

This is a great opportunity to create our own otp process (application? idk), getting our feet wet with the Erlang actor model.

@seejee if you end up taking this on, I'd love it to end up as a PR so we can all view it and ask questions about it! 

(you should feel free to deploy that PR though, regardless.)

**Comment by srobbibaro** [comment]
As a general rule of thumb, I'd say outside of any 10% time and mob programming, we're about at the point where I think working in branches and using PRs make sense for a number of reasons, so let's make it a goal!
