### ISSUE TITLE
add winters wizard as mascot

### ISSUE THREAD

**Issue by joelmccracken** [thinkthroughmath/dev_wizard#12]

**Comment by joelmccracken** [comment]
![the-dev-wizard](https://cloud.githubusercontent.com/assets/10936/12276109/e4e1fb06-b941-11e5-80e8-76c6b54c9686.png)

**Comment by srobbibaro** [comment]
Yep - first thing to do in 10% time!

**Comment by joelmccracken** [comment]
doneee
