### ISSUE TITLE
Move off of Heroku.

### ISSUE THREAD

**Issue by seejee** [thinkthroughmath/dev_wizard#16]
This will give us experience deploying Elixir apps "for real".

**Comment by srobbibaro** [comment]
We should get @BobTheBotMaker involved when we are serious about doing this.  For the time being, I'm going to prioritize this a bit lower than some of the other issues on the board since we're still actively prototyping and heroku is "free" and "easy."

**Comment by srobbibaro** [comment]
After discussion with Joel, the priority of this ticket will be tied to our other potential elixir initiatives - will upgrade priority, and escalate further if needed.

**Comment by seejee** [comment]
Yeah, I'd like this done sooner rather than later so the barrier to entry for a "real" elixir app is lower.

**Comment by srobbibaro** [comment]
:+1:

**Comment by srobbibaro** [comment]
We're not going to migrate off of Heroku at this time; closing.
