### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by srobbibaro** [thinkthroughmath/dev_wizard#19]
Let's implement CI into our build process.

AC: 
- Build triggered when code is pushed to "master" branch
- Tests are run
- Result is emailed to "interested" parties

**Comment by seejee** [comment]
Wanna use Travis or stick with Jenkins?

**Comment by joelmccracken** [comment]
oo travis! but jenkins would fit in line with what we will do here.

**Comment by joelmccracken** [comment]
for our own internal projects

**Comment by srobbibaro** [comment]
I'd love to get people's opinions on this, but I'm liking travis, personally.
