### ISSUE TITLE
confusing behavior of "my_code_reviews" page

### ISSUE THREAD

**Issue by joelmccracken** [thinkthroughmath/dev_wizard#53]
There is a PR that is labeled "passed code review" for me, although it actually needs review. This is because I had added LGTM to the PR earlier, before more commits were added. 

For reference, the PR that this issue manifested itself on is: https://github.com/thinkthroughmath/apangea/pull/3353

**Comment by srobbibaro** [comment]
Since we now support Github's review system, no longer use "LGTM" for signing off on reviews. Closing.
